<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CameraScrollFix</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <Version>1.0.3</Version>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="..\..\REFERENCES\*.dll" />
  </ItemGroup>
  <Target Name="CopyToPlugins" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="../CameraScrollFix/plugins" />
  </Target>
</Project>
